# Macro file for "LaBr3_v4.cc"
#

/testem/det/setLaBr3Diam 3.0 cm
/testem/det/setLaBr3Length 5.0 cm
/testem/det/setGapThickness 0.1 cm
/testem/det/setGapMaterial G4_TEFLON
/testem/det/setAlCaseThickness 0.2 cm
/testem/det/setPbCaseThickness 0.5 cm
/testem/det/setPMTDiameter 8.0 cm
/testem/det/setPMTLength 25.0 cm
/testem/det/update

/run/initialize
#
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 13. cm
/gps/ang/type iso
/gps/energy 6.13 MeV

/run/beamOn 320000
